GET https://human-tech-hackaton-22.vercel.app/api/computer-code

### computer pollObject
GET https://human-tech-hackaton-22.vercel.app/api/computer-poll_object

### computer pollObject
POST https://human-tech-hackaton-22.vercel.app/api/computer-poll_object
Content-Type: application/json

{
	"yesChange": "1",
	"noChange": "0"
}

### codeplasty transparency-one
POST https://human-tech-hackaton-22.vercel.app/api/codeplasty-transparency-one
Content-Type: application/json

{"transparencyOneChange":"1"}

### codeplasty transparency-one
GET https://human-tech-hackaton-22.vercel.app/api/codeplasty-transparency-one
